# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qpylotwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QPyLOTWindow(object):
    def setupUi(self, QPyLOTWindow):
        QPyLOTWindow.setObjectName("QPyLOTWindow")
        QPyLOTWindow.resize(695, 578)
        self.centralWidget = QtWidgets.QWidget(QPyLOTWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.MaintabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.MaintabWidget.setObjectName("MaintabWidget")
        self.Plot2Dtab = QtWidgets.QWidget()
        self.Plot2Dtab.setObjectName("Plot2Dtab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Plot2Dtab)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Plot2DlistWidget = QtWidgets.QListWidget(self.Plot2Dtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Plot2DlistWidget.sizePolicy().hasHeightForWidth())
        self.Plot2DlistWidget.setSizePolicy(sizePolicy)
        self.Plot2DlistWidget.setObjectName("Plot2DlistWidget")
        item = QtWidgets.QListWidgetItem()
        self.Plot2DlistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Plot2DlistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Plot2DlistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Plot2DlistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Plot2DlistWidget.addItem(item)
        self.gridLayout_2.addWidget(self.Plot2DlistWidget, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.Plot2DstackedWidget = QtWidgets.QStackedWidget(self.Plot2Dtab)
        self.Plot2DstackedWidget.setObjectName("Plot2DstackedWidget")
        self.Plot2DDatapage = QtWidgets.QWidget()
        self.Plot2DDatapage.setObjectName("Plot2DDatapage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Plot2DDatapage)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Filelabel = QtWidgets.QLabel(self.Plot2DDatapage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Filelabel.sizePolicy().hasHeightForWidth())
        self.Filelabel.setSizePolicy(sizePolicy)
        self.Filelabel.setObjectName("Filelabel")
        self.gridLayout_3.addWidget(self.Filelabel, 1, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 5, 1, 1, 1)
        self.Y1lineEdit = QtWidgets.QLineEdit(self.Plot2DDatapage)
        self.Y1lineEdit.setObjectName("Y1lineEdit")
        self.gridLayout_3.addWidget(self.Y1lineEdit, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.Plot2DDatapage)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 4, 0, 1, 4)
        self.Y1comboBox = QtWidgets.QComboBox(self.Plot2DDatapage)
        self.Y1comboBox.setEnabled(False)
        self.Y1comboBox.setObjectName("Y1comboBox")
        self.gridLayout_3.addWidget(self.Y1comboBox, 3, 3, 1, 1)
        self.Y1pushButton = QtWidgets.QPushButton(self.Plot2DDatapage)
        self.Y1pushButton.setObjectName("Y1pushButton")
        self.gridLayout_3.addWidget(self.Y1pushButton, 3, 2, 1, 1)
        self.Columnlabel = QtWidgets.QLabel(self.Plot2DDatapage)
        self.Columnlabel.setObjectName("Columnlabel")
        self.gridLayout_3.addWidget(self.Columnlabel, 1, 3, 1, 1)
        self.X1pushButton = QtWidgets.QPushButton(self.Plot2DDatapage)
        self.X1pushButton.setObjectName("X1pushButton")
        self.gridLayout_3.addWidget(self.X1pushButton, 2, 2, 1, 1)
        self.Y1label = QtWidgets.QLabel(self.Plot2DDatapage)
        self.Y1label.setObjectName("Y1label")
        self.gridLayout_3.addWidget(self.Y1label, 3, 0, 1, 1)
        self.X1comboBox = QtWidgets.QComboBox(self.Plot2DDatapage)
        self.X1comboBox.setEnabled(False)
        self.X1comboBox.setObjectName("X1comboBox")
        self.gridLayout_3.addWidget(self.X1comboBox, 2, 3, 1, 1)
        self.X1label = QtWidgets.QLabel(self.Plot2DDatapage)
        self.X1label.setObjectName("X1label")
        self.gridLayout_3.addWidget(self.X1label, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.Plot2DDatapage)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 7, 1, 1, 1)
        self.X1FilelineEdit = QtWidgets.QLineEdit(self.Plot2DDatapage)
        self.X1FilelineEdit.setObjectName("X1FilelineEdit")
        self.gridLayout_3.addWidget(self.X1FilelineEdit, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.Plot2DDatapage)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 6, 1, 1, 1)
        self.Plot2DstackedWidget.addWidget(self.Plot2DDatapage)
        self.Plot2DAxespage = QtWidgets.QWidget()
        self.Plot2DAxespage.setObjectName("Plot2DAxespage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Plot2DAxespage)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.YticsMinorspinBox = QtWidgets.QSpinBox(self.Plot2DAxespage)
        self.YticsMinorspinBox.setEnabled(False)
        self.YticsMinorspinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsMinorspinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsMinorspinBox.setObjectName("YticsMinorspinBox")
        self.gridLayout_8.addWidget(self.YticsMinorspinBox, 5, 2, 1, 1)
        self.YticsLengthdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.Plot2DAxespage)
        self.YticsLengthdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsLengthdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsLengthdoubleSpinBox.setProperty("value", 5.0)
        self.YticsLengthdoubleSpinBox.setObjectName("YticsLengthdoubleSpinBox")
        self.gridLayout_8.addWidget(self.YticsLengthdoubleSpinBox, 4, 4, 1, 1)
        self.YticsRightcheckBox = QtWidgets.QCheckBox(self.Plot2DAxespage)
        self.YticsRightcheckBox.setChecked(True)
        self.YticsRightcheckBox.setObjectName("YticsRightcheckBox")
        self.gridLayout_8.addWidget(self.YticsRightcheckBox, 4, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Plot2DAxespage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 3, 1, 1, 1)
        self.XticsMinorspinBox = QtWidgets.QSpinBox(self.Plot2DAxespage)
        self.XticsMinorspinBox.setEnabled(False)
        self.XticsMinorspinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsMinorspinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsMinorspinBox.setObjectName("XticsMinorspinBox")
        self.gridLayout_8.addWidget(self.XticsMinorspinBox, 2, 2, 1, 1)
        self.YticslineEdit = QtWidgets.QLineEdit(self.Plot2DAxespage)
        self.YticslineEdit.setObjectName("YticslineEdit")
        self.gridLayout_8.addWidget(self.YticslineEdit, 4, 1, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.Plot2DAxespage)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 6, 1, 1, 1)
        self.XticslineEdit = QtWidgets.QLineEdit(self.Plot2DAxespage)
        self.XticslineEdit.setObjectName("XticslineEdit")
        self.gridLayout_8.addWidget(self.XticslineEdit, 1, 1, 1, 2)
        self.YticsMinorLengthdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.Plot2DAxespage)
        self.YticsMinorLengthdoubleSpinBox.setEnabled(False)
        self.YticsMinorLengthdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsMinorLengthdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsMinorLengthdoubleSpinBox.setObjectName("YticsMinorLengthdoubleSpinBox")
        self.gridLayout_8.addWidget(self.YticsMinorLengthdoubleSpinBox, 5, 4, 1, 1)
        self.XticsLengthdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.Plot2DAxespage)
        self.XticsLengthdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsLengthdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsLengthdoubleSpinBox.setProperty("value", 5.0)
        self.XticsLengthdoubleSpinBox.setObjectName("XticsLengthdoubleSpinBox")
        self.gridLayout_8.addWidget(self.XticsLengthdoubleSpinBox, 1, 4, 1, 1)
        self.YticsMinorcheckBox = QtWidgets.QCheckBox(self.Plot2DAxespage)
        self.YticsMinorcheckBox.setObjectName("YticsMinorcheckBox")
        self.gridLayout_8.addWidget(self.YticsMinorcheckBox, 5, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.Plot2DAxespage)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_8.addWidget(self.checkBox_4, 4, 6, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.Plot2DAxespage)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_8.addWidget(self.line_3, 0, 1, 1, 6)
        self.XticsBottomcheckBox = QtWidgets.QCheckBox(self.Plot2DAxespage)
        self.XticsBottomcheckBox.setChecked(True)
        self.XticsBottomcheckBox.setObjectName("XticsBottomcheckBox")
        self.gridLayout_8.addWidget(self.XticsBottomcheckBox, 1, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.Plot2DAxespage)
        self.label_11.setEnabled(False)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 5, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.Plot2DAxespage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 1, 3, 1, 1)
        self.XticsTopcheckBox = QtWidgets.QCheckBox(self.Plot2DAxespage)
        self.XticsTopcheckBox.setChecked(True)
        self.XticsTopcheckBox.setObjectName("XticsTopcheckBox")
        self.gridLayout_8.addWidget(self.XticsTopcheckBox, 1, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Plot2DAxespage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.Plot2DAxespage)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Plot2DAxespage)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Plot2DAxespage)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 2, 3, 1, 1)
        self.XticsMinorLengthdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.Plot2DAxespage)
        self.XticsMinorLengthdoubleSpinBox.setEnabled(False)
        self.XticsMinorLengthdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsMinorLengthdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsMinorLengthdoubleSpinBox.setObjectName("XticsMinorLengthdoubleSpinBox")
        self.gridLayout_8.addWidget(self.XticsMinorLengthdoubleSpinBox, 2, 4, 1, 1)
        self.YticsOffsetdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.Plot2DAxespage)
        self.YticsOffsetdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YticsOffsetdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YticsOffsetdoubleSpinBox.setObjectName("YticsOffsetdoubleSpinBox")
        self.gridLayout_8.addWidget(self.YticsOffsetdoubleSpinBox, 6, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Plot2DAxespage)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 4, 3, 1, 1)
        self.XticsMinorcheckBox = QtWidgets.QCheckBox(self.Plot2DAxespage)
        self.XticsMinorcheckBox.setObjectName("XticsMinorcheckBox")
        self.gridLayout_8.addWidget(self.XticsMinorcheckBox, 2, 1, 1, 1)
        self.XticsOffsetdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.Plot2DAxespage)
        self.XticsOffsetdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XticsOffsetdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XticsOffsetdoubleSpinBox.setObjectName("XticsOffsetdoubleSpinBox")
        self.gridLayout_8.addWidget(self.XticsOffsetdoubleSpinBox, 3, 2, 1, 1)
        self.YticsFonttoolButton = QtWidgets.QToolButton(self.Plot2DAxespage)
        self.YticsFonttoolButton.setObjectName("YticsFonttoolButton")
        self.gridLayout_8.addWidget(self.YticsFonttoolButton, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.Plot2DAxespage)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 7, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_8, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem2, 5, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.YLabeloffsetdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.Plot2DAxespage)
        self.YLabeloffsetdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.YLabeloffsetdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.YLabeloffsetdoubleSpinBox.setObjectName("YLabeloffsetdoubleSpinBox")
        self.gridLayout_7.addWidget(self.YLabeloffsetdoubleSpinBox, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Plot2DAxespage)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 2, 2, 1, 1)
        self.Labelslabel = QtWidgets.QLabel(self.Plot2DAxespage)
        self.Labelslabel.setObjectName("Labelslabel")
        self.gridLayout_7.addWidget(self.Labelslabel, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.Plot2DAxespage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 1, 2, 1, 1)
        self.XLabeloffsetdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.Plot2DAxespage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XLabeloffsetdoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.XLabeloffsetdoubleSpinBox.setSizePolicy(sizePolicy)
        self.XLabeloffsetdoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.XLabeloffsetdoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.XLabeloffsetdoubleSpinBox.setObjectName("XLabeloffsetdoubleSpinBox")
        self.gridLayout_7.addWidget(self.XLabeloffsetdoubleSpinBox, 1, 3, 1, 1)
        self.YLabellabel = QtWidgets.QLabel(self.Plot2DAxespage)
        self.YLabellabel.setObjectName("YLabellabel")
        self.gridLayout_7.addWidget(self.YLabellabel, 2, 0, 1, 1)
        self.XLabellabel = QtWidgets.QLabel(self.Plot2DAxespage)
        self.XLabellabel.setObjectName("XLabellabel")
        self.gridLayout_7.addWidget(self.XLabellabel, 1, 0, 1, 1)
        self.YLabellineEdit = QtWidgets.QLineEdit(self.Plot2DAxespage)
        self.YLabellineEdit.setObjectName("YLabellineEdit")
        self.gridLayout_7.addWidget(self.YLabellineEdit, 2, 1, 1, 1)
        self.XLabellineEdit = QtWidgets.QLineEdit(self.Plot2DAxespage)
        self.XLabellineEdit.setObjectName("XLabellineEdit")
        self.gridLayout_7.addWidget(self.XLabellineEdit, 1, 1, 1, 1)
        self.Fontlabel = QtWidgets.QLabel(self.Plot2DAxespage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fontlabel.sizePolicy().hasHeightForWidth())
        self.Fontlabel.setSizePolicy(sizePolicy)
        self.Fontlabel.setObjectName("Fontlabel")
        self.gridLayout_7.addWidget(self.Fontlabel, 3, 0, 1, 1)
        self.LabelFonttoolButton = QtWidgets.QToolButton(self.Plot2DAxespage)
        self.LabelFonttoolButton.setObjectName("LabelFonttoolButton")
        self.gridLayout_7.addWidget(self.LabelFonttoolButton, 3, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.Plot2DAxespage)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 0, 1, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout_7, 4, 0, 1, 1)
        self.Plot2DstackedWidget.addWidget(self.Plot2DAxespage)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 70, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.Plot2DstackedWidget.addWidget(self.page)
        self.gridLayout_2.addWidget(self.Plot2DstackedWidget, 0, 1, 1, 1)
        self.MaintabWidget.addTab(self.Plot2Dtab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.MaintabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.MaintabWidget, 0, 0, 1, 1)
        QPyLOTWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(QPyLOTWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 695, 22))
        self.menuBar.setObjectName("menuBar")
        QPyLOTWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(QPyLOTWindow)
        self.statusBar.setObjectName("statusBar")
        QPyLOTWindow.setStatusBar(self.statusBar)
        self.mainToolBar = QtWidgets.QToolBar(QPyLOTWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        QPyLOTWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(QPyLOTWindow)
        self.Plot2DstackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(QPyLOTWindow)

    def retranslateUi(self, QPyLOTWindow):
        _translate = QtCore.QCoreApplication.translate
        QPyLOTWindow.setWindowTitle(_translate("QPyLOTWindow", "QPyLOT"))
        __sortingEnabled = self.Plot2DlistWidget.isSortingEnabled()
        self.Plot2DlistWidget.setSortingEnabled(False)
        item = self.Plot2DlistWidget.item(0)
        item.setText(_translate("QPyLOTWindow", "Data"))
        item = self.Plot2DlistWidget.item(1)
        item.setText(_translate("QPyLOTWindow", "Axes"))
        item = self.Plot2DlistWidget.item(2)
        item.setText(_translate("QPyLOTWindow", "Markers"))
        item = self.Plot2DlistWidget.item(3)
        item.setText(_translate("QPyLOTWindow", "Legend"))
        item = self.Plot2DlistWidget.item(4)
        item.setText(_translate("QPyLOTWindow", "Text"))
        self.Plot2DlistWidget.setSortingEnabled(__sortingEnabled)
        self.Filelabel.setText(_translate("QPyLOTWindow", "File (ASCII or FITS table)"))
        self.Y1pushButton.setText(_translate("QPyLOTWindow", "Open"))
        self.Columnlabel.setText(_translate("QPyLOTWindow", "Column"))
        self.X1pushButton.setText(_translate("QPyLOTWindow", "Open"))
        self.Y1label.setText(_translate("QPyLOTWindow", "Y"))
        self.X1label.setText(_translate("QPyLOTWindow", "X  "))
        self.pushButton.setText(_translate("QPyLOTWindow", "PushButton"))
        self.pushButton_2.setText(_translate("QPyLOTWindow", "PushButton"))
        self.YticsRightcheckBox.setText(_translate("QPyLOTWindow", "Left"))
        self.label_5.setText(_translate("QPyLOTWindow", "Label offset"))
        self.label_10.setText(_translate("QPyLOTWindow", "Label offset"))
        self.YticsMinorcheckBox.setText(_translate("QPyLOTWindow", "Minor tics"))
        self.checkBox_4.setText(_translate("QPyLOTWindow", "Right"))
        self.XticsBottomcheckBox.setText(_translate("QPyLOTWindow", "Bottom"))
        self.label_11.setText(_translate("QPyLOTWindow", "Length"))
        self.label_6.setText(_translate("QPyLOTWindow", "Length"))
        self.XticsTopcheckBox.setText(_translate("QPyLOTWindow", "Top"))
        self.label_4.setText(_translate("QPyLOTWindow", "  X tics:"))
        self.label_8.setText(_translate("QPyLOTWindow", "  Y tics:"))
        self.label_3.setText(_translate("QPyLOTWindow", "TICS      "))
        self.label_7.setText(_translate("QPyLOTWindow", "Length"))
        self.label_9.setText(_translate("QPyLOTWindow", "Length"))
        self.XticsMinorcheckBox.setText(_translate("QPyLOTWindow", " Minor tics"))
        self.YticsFonttoolButton.setText(_translate("QPyLOTWindow", "Helvetica, 12 pt"))
        self.label_12.setText(_translate("QPyLOTWindow", "  Font"))
        self.label_2.setText(_translate("QPyLOTWindow", "Offset"))
        self.Labelslabel.setText(_translate("QPyLOTWindow", "LABELS"))
        self.label.setText(_translate("QPyLOTWindow", "Offset"))
        self.YLabellabel.setText(_translate("QPyLOTWindow", "  Y label:"))
        self.XLabellabel.setText(_translate("QPyLOTWindow", "  X label:"))
        self.Fontlabel.setText(_translate("QPyLOTWindow", "  Font:"))
        self.LabelFonttoolButton.setText(_translate("QPyLOTWindow", "Helvetica, 12 pt"))
        self.pushButton_3.setText(_translate("QPyLOTWindow", "PushButton"))
        self.MaintabWidget.setTabText(self.MaintabWidget.indexOf(self.Plot2Dtab), _translate("QPyLOTWindow", "2D Plot"))
        self.MaintabWidget.setTabText(self.MaintabWidget.indexOf(self.tab_2), _translate("QPyLOTWindow", "Tab 2"))

