#!/bin/bash

PYUIC=pyuic5

$PYUIC -o moc/ui_start.py UIs/start_window.ui
$PYUIC -o moc/ui_plot1d.py UIs/plot1d.ui
$PYUIC -o moc/ui_plot1d_tabw.py UIs/plot1d_tabw.ui


$PYUIC -o moc/ui_dummy.py UIs/dummy.ui
